# Generated by Django 5.1.4 on 2025-03-20 06:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_theater_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
